/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.MDP.Formula_1;

import it.unicam.cs.MDP.Formula_1.View.View;

import java.io.*;
import java.util.Scanner;

public class App {
    public static void main(String[] args) throws IOException {
        View view = new View();
        view.open();
        view.close();
    }
}
